spring:
  application:
    name: msa-graphql

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true