spring:
  application:
    name: msa-graphql

  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql


management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3_multi
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

  endpoints:
    web:
      exposure:
        include:
          - circuitbreakers
          - info
          - health
          - loggers
          - mappings
          - metrics
          - shutdown
          - prometheus
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
    fetch-registry: true