version: '3.8'
volumes:
  redis-data:


services:
  next-campus-mysql:
    image: mysql:8.0
    container_name: next-campus-mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fast
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  next-campus-redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
