apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-discovery
  labels:
    app: msa-discovery
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: msa-discovery
  template:
    metadata:
      labels:
        app: msa-discovery
    spec:
      containers:
        - name: msa-discovery
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            { { - toYaml .Values.resources | nindent 12 } }