spring:
  application:
    name: msa-course-service

  datasource:
    url: jdbc:mysql://183.111.67.163:3306/db?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db
    password: db123!@#


  jpa:
    defer-datasource-initialization: true # hibernate ??? ?? data.sql ???? ??
    database-platform: org.hibernate.dialect.MySQL8Dialect # mysql ??
    show-sql: true # sql ?? ????
    hibernate:
      ddl-auto: none # ?????? ??? ?? ?? ??
    properties:
      hibernate:
        format_sql: true # sql ??? ??? ????
        use_sql_comments: true # ???? ???

  sql:
    init:
      data-locations: classpath:sql/data.sql # sql ??? /resources/sql/data.sql ??
      schema-locations: classpath:sql/schema-mysql.sql # ??? ??
      mode: never

eureka:
  client:
    service-url:
      defaultZone: http://msa-discovery:8000/eureka/ # ?????????
    register-with-eureka: true
    fetch-registry: true