spring:
  application:
    name: msa-course-chat-service

  data:
    redis:
      port: 6380
      host: 127.0.0.1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
    registerWithEureka: true
    fetchRegistry: true


grpc:
  server:
    port: 9006

server:
  port: 8006