apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-course-service
  labels:
    app: msa-course-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: msa-course-service
  template:
    metadata:
      labels:
        app: msa-course-service
    spec:
      containers:
        - name: msa-course-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            { { - toYaml .Values.resources | nindent 12 } }